### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Tommixoft** [Ksantor/plugin.video.lostfilm.tv#1]
Im creating issue here to not use original repo for this version :) Anyways not working. As i said strange that even static menus like "My Library" is not visible in plugin. Did you remove it?

**Comment by Ksantor** [comment]
@Tommixoft, just to be clear, do you have any series added to your library on the **lostfilm.tv webpage**?

Something like that:

<img width="756" alt="screen shot 2017-02-05 at 21 28 39" src="https://cloud.githubusercontent.com/assets/4328879/22629194/24674214-ebea-11e6-885c-5c76fcf4c2f0.png">

Plugin reads only you "favourites" ("избранные") from the **lostfilm.tv**, not from the local Kodi library.

About all the context menus - yes, removed them for now. I plan to re add them a little later.

**Comment by Tommixoft** [comment]
Ohhhhhhh.... did not know that. So from now only via website i should add my favorites?

**Comment by Tommixoft** [comment]
Yes i confirm when added to favorites it shows it. But PLS you MUST add All Shows to be accessible from Kodi. :) Sometimes it's super handy. Also my mom shes almost 60 y/o loves to use via kodi not from website :DD Anyways i like your work! Very fast! Thanks.

**Comment by Ksantor** [comment]
@Tommixoft for now - yes, only lostfilm library.

Probably I'll manage to enable local Kodi library, and series browsing, just like in the original plugin version. It's just it was faster to implement it this way.

Wanted to get things working again ASAP.

Overall, there are lots of things yet to be done, including caching, series/episodes info, proxy servers, background library update etc.

P.S. Since lostfilm.tv just updated their web UI, it is possible, that there will be some changes and/or bug fixes in the nearest future. Plugin may break again because of these changes. So don't hesitate to open new issues.

P.P.S. I'm not a Python developer, so please don't expect super fast results from me.

**Comment by Tommixoft** [comment]
Ps im very happy that it shows original title. Russian people MAYBE will not be so happy. But i think having original title in front is important, cause people even if they are russians knows better original title, not translation. So far very nice changes! :)

Im saying that you very fast doing things, im not expecting fast :) You do it fast and im jealous :)

**Comment by Ksantor** [comment]
`im very happy that it shows original title` - this feature was in the original plugin, though, I believe it was broken (or maybe not, really don't remember).

There is an option in plugin settings - "Show original title".

Closing this issue, since the question with library is solved.
